# Generated by Django 3.1.2 on 2020-11-03 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('FSUID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('office', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('FSUID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=3)),
                ('number_id', models.CharField(max_length=4)),
                ('section', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('CSBS_Req', models.BooleanField(default=False)),
                ('CSBS_Elec', models.BooleanField(default=False)),
                ('CSBA_Req', models.BooleanField(default=False)),
                ('CSBA_Elec', models.BooleanField(default=False)),
                ('time_start', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('enrollment_capacity', models.IntegerField()),
                ('enrollment_number', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=10, null=True)),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
