# Generated by Django 3.1.2 on 2020-11-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='hasRecitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='recitation_location',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='recitation_time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='recitation_time_start',
            field=models.TimeField(null=True),
        ),
    ]
