# Generated by Django 3.1.2 on 2020-11-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20201102_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='CSBA_Elec',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='CSBA_Req',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='CSBS_Elec',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='CSBS_Req',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='recitation_location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='recitation_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='recitation_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='office',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
