# Generated by Django 3.1.2 on 2020-11-17 21:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20201103_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='id',
        ),
        migrations.AddField(
            model_name='class',
            name='course_reference_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='hello', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 4, 23)),
        ),
        migrations.AlterField(
            model_name='class',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 1, 6)),
        ),
        migrations.AlterField(
            model_name='class',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.professor'),
        ),
        migrations.CreateModel(
            name='Enrolled_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FSUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.student')),
                ('course_reference_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
            ],
        ),
    ]
