# Generated by Django 3.1.2 on 2020-11-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20201117_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='recommended_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='course_reference_number',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.IntegerField(),
        ),
    ]
