# Generated by Django 3.1.2 on 2020-11-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20201117_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='CSBA_Elec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='CSBA_Req',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='CSBS_Elec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='CSBS_Req',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='recitation_location',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='office',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
