# Generated by Django 3.1.2 on 2020-11-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_auto_20201118_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='recitation_location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='office',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
