# Generated by Django 3.1.2 on 2020-11-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20201118_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='recitation_location',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='professor',
            name='office',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
