# Generated by Django 3.1.2 on 2020-11-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_auto_20201118_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='description',
        ),
    ]
