# Generated by Django 3.1.2 on 2020-11-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_remove_class_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
